### ISSUE TITLE
Make it mobile responsive

### ISSUE THREAD

**Issue by mateusmeloxyz** [mateusgomes01/landing-page-template#1]
That's it. Nothing to add

**Comment by prakhar2010030** [comment]
Hi, will you assign it to me???

**Comment by Tomiloba2** [comment]
hello, can I work on this??

**Comment by mateusmeloxyz** [comment]
@prakhar2010030 @Tomiloba2 feel free to work on it. I've added both of you as colaborators on this repo.

You may also fork it and create a pull request later if prefered

**Comment by Tomiloba2** [comment]
Thanks alot

**Comment by maanil17** [comment]
can i work on this one?

**Comment by mateusmeloxyz** [comment]
@maanil17 Yes. I've added you as a colaborator. You may also fork it and create a PR later.

**Comment by mateusmeloxyz** [comment]
Solved #2
